# Generated by Django 3.2.9 on 2022-04-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='galley')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
